services:
  db:
    image: postgres:latest
    ports:
      - '${DATABASE_PORT}:5432'
    container_name: promptiXdb
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
